# Introduction to Python for Machine Learning

Electric Utilities report a huge amount of information to government and public agencies. They include very granular data on fuel burned, electricity generated, power plant usage patterns, plant capacity factors and emissions from greenhouse gases. However, this data is not well documented and sometimes they are provided in a format that makes it difficult to understand.

This course  explores how  machine learning techniques can be an invaluable tool for **solving one of the grand challenges posed to humanity** -  <a href="https://hamoye.com/app/course-details/11993f74d1c1f000" target="_blank">climate change</a>



As mentioned previously, NumPy is a library that has ndarray as its basic data structure used to handle arrays and matrices. A NumPy array has a grid of values all of which are of the same data type, mostly integers and floats. These arrays can also be created from Python lists. Below are some examples:

#### Convention for importing numpy. 

Incase you are working on your local jupyter notebook esure that you have downloaded Numpy. You can do this  by walking through the instructions <a href="https://phoenixnap.com/kb/install-numpy" target="_blank">here</a>

In [2]:
import numpy as np


In [3]:
arr = [6, 7, 8, 9]
print(type(arr)) # helps see the datatype of this
print(arr)

<class 'list'>
[6, 7, 8, 9]


In [4]:
a = np.array(arr)
print(type(a))
print(a.shape)
print(a.dtype)
print(a)

<class 'numpy.ndarray'>
(4,)
int64
[6 7 8 9]


In [5]:
print(a.ndim)

1


In [6]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [7]:
b = np.array([[1, 2, 3], [4, 5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


There are also some inbuilt functions that can be used to initialize numpy which include empty(), zeros(), ones(), full(), random.random().

#### More details on the use of numpy inbuilt functions can be read from this <a href="https://numpy.org/doc/1.19/user/basics.html" target="_blank">link</a>

In [8]:
np.random.random((2, 3)) 

array([[0.22280404, 0.03972961, 0.28003622],
       [0.82466897, 0.36438397, 0.89258081]])

In [9]:
np.zeros((2, 3)) #prints a matrix with shape 2 by 3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.zeros(3)# prints an array of size 3

array([0., 0., 0.])

In [12]:
np.eye(3) # prints the identity matrix you can use the other code below:

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
np.identity(3) # this works the same way as eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Intra-operability of arrays and scalars.

Vectorisation in numpy arrays allows for faster processing by eliminating for loops when dealing with arrays of equal shape. This allows for batch arithmetic operations on the arrays by applying the operator elementwise. Similarly, scalars are also propagated element-wise across an array. For arrays with different sizes, it is impossible to perform element-wise operations instead, numpy handles this by broadcasting provided the dimensions of the arrays are the same or, one of the dimensions of the array is 1.


In [13]:
c = np.array([[9.0, 8.0, 7.0], [1.0, 2.0, 3.0]])
d = np.array([[4.0, 5.0, 6.0], [9.0, 8.0, 7.0]])

In [14]:
c + d

array([[13., 13., 13.],
       [10., 10., 10.]])

In [15]:
c*d

array([[36., 40., 42.],
       [ 9., 16., 21.]])

In [16]:
5/d

array([[1.25      , 1.        , 0.83333333],
       [0.55555556, 0.625     , 0.71428571]])

In [17]:
c ** 2

array([[81., 64., 49.],
       [ 1.,  4.,  9.]])

## Indexing with arrays & using arrays for data processing.

The elements in the example arrays above can be accessed by indexing like lists in Python such that:


In [18]:
a[0] = 6
a

array([6, 7, 8, 9])

Python begns its count from  0 and so if one wants to access the first element in the first list, you index as show in the previous chunk of code.

In [19]:
a[3] # Selects the 2nd element in your list

9

In [20]:
b[0,0] # selects the first element in the row and first on the colum

1

In [21]:
b[1, 2] # selects the element on 1st row 2nd column

6

Elements in arrays  can also be retrieved by slicing rows and columns or a combination of indexing and slicing.

In [28]:
d[1, 0:2] # The numbers before the comma refers to the rows whereas the elements after  it is indexing the columns

array([9., 8.])

In [23]:
e = np.array([[10, 11, 12],
               [13, 14, 15], [16, 17, 18], [19, 20, 21]])
e

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [24]:
e[:3, :2] 
# selects rows from start to leaving out the 3rd row.
# selects columns from start leaving out the 2nd

array([[10, 11],
       [13, 14],
       [16, 17]])

There are other advanced methods of indexing which are shown below.



In [25]:
e[[2, 0, 3, 1], [2, 1, 0, 2]]

array([18, 11, 19, 15])

In [26]:
e[e>15]# THis will return all elements that are greater than 15

array([16, 17, 18, 19, 20, 21])